name: discussion
description: A new Flutter project.
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: any
  flutter_device_type: ^0.4.0
  flutter_overboard: 1.1.5
  flutter_screenutil: ^4.0.3+3
  flutter_spinkit: ^5.0.0
  flutter_svg: any
  flutter_swiper: ^1.1.6
  fluttertoast: ^7.1.8
  get: ^4.1.1
  http: ^0.13.1
  image_picker: ^0.7.4
  mime: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  agora_rtc_engine: ^3.3.3
  permission_handler: ^7.1.0
  getwidget: ^1.2.4
  stop_watch_timer: ^1.1.0+1
  in_app_purchase: ^0.3.5+1
  share: ^2.0.4
  flutter_blurhash: ^0.6.0
  rflutter_alert: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  sdp_transform: ^0.3.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/translate/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cocogoose
      fonts:
        - asset: assets/fonts/Cocogoose-Classic.ttf
